name: Build exe file

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.13'
          pyinstaller_ver: '==6.14.2'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "mcmods-sync-cli", --paths "./src", --windowed
          spec_options: # any custom arguments you want like: `--debug`